# Generated by Django 5.0.6 on 2024-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_charts', '0002_savedchart_chart_image_alter_savedchart_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedchart',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
