# Generated by Django 5.0.2 on 2024-07-04 05:49

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_query', models.TextField()),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to=feedback.models.upload_to)),
                ('reaction', models.CharField(blank=True, max_length=15, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
