# Generated by Django 5.0.4 on 2024-07-01 17:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to=users.models.upload_to),
        ),
    ]
