# Generated by Django 5.0.6 on 2024-07-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_coverpicture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
