<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-07 05:18
=======
# Generated by Django 5.0.4 on 2024-07-07 10:21
>>>>>>> 1b5165a69edb9cda6749681ad31997f0a75967a9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_coverpicture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
