# Generated by Django 5.0.4 on 2024-07-10 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectDb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connecteddatabase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataanalysisresult',
            name='connected_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectDb.connecteddatabase'),
        ),
    ]
