# Generated by Django 5.0.4 on 2024-06-12 20:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_firstname_user_gender_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='default.png', upload_to=users.models.upload_to),
        ),
    ]
