# Generated by Django 5.0.6 on 2024-06-19 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_charts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedchart',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AlterField(
            model_name='savedchart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
