# Generated by Django 5.0.4 on 2024-07-07 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectDb', '0001_initial'),
        ('myapp', '0002_savedchart_updated_at_alter_savedchart_chart_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedchart',
            name='database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to='connectDb.connecteddatabase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedchart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
