# Generated by Django 5.0.4 on 2024-07-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_savedchart_database_alter_savedchart_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedchart',
            old_name='created_by',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='savedchart',
            old_name='database',
            new_name='database_id',
        ),
    ]
