# Generated by Django 5.0.4 on 2024-07-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_created_by_savedchart_created_by_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedchart',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='savedchart',
            old_name='database_id',
            new_name='database',
        ),
    ]
