# Generated by Django 5.0.4 on 2024-07-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0001_initial'),
        ('connectDb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='connectDb.connecteddatabase'),
        ),
    ]
